# Generated by Django 4.1 on 2022-08-30 05:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(max_length=180)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 8, 30, 5, 18, 0, 334812))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2022, 8, 30, 5, 18, 0, 334821))),
            ],
            options={
                'db_table': 'genres',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('manufacturer', models.CharField(max_length=60)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 8, 30, 5, 18, 0, 335329))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2022, 8, 30, 5, 18, 0, 335334))),
            ],
            options={
                'db_table': 'platforms',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_name', models.CharField(max_length=60, unique=True)),
                ('founded', models.DateField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 8, 30, 5, 18, 0, 335102))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2022, 8, 30, 5, 18, 0, 335108))),
            ],
            options={
                'db_table': 'publishers',
                'ordering': ['trade_name'],
            },
        ),
        migrations.CreateModel(
            name='VideoGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('published_year', models.DateField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 8, 30, 5, 18, 0, 335561))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2022, 8, 30, 5, 18, 0, 335568))),
                ('genres', models.ManyToManyField(blank=True, null=True, related_name='games', to='gamedata.genre')),
                ('platform', models.ManyToManyField(blank=True, null=True, related_name='games', to='gamedata.platform')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='gamedata.publisher')),
            ],
            options={
                'db_table': 'videogames',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='publisher',
            index=models.Index(fields=['trade_name'], name='trade_name_idx'),
        ),
        migrations.AddIndex(
            model_name='platform',
            index=models.Index(fields=['name'], name='platform_name_idx'),
        ),
        migrations.AddIndex(
            model_name='genre',
            index=models.Index(fields=['name'], name='genre_name_idx'),
        ),
        migrations.AddIndex(
            model_name='videogame',
            index=models.Index(fields=['published_year'], name='pub_year_idx'),
        ),
        migrations.AddIndex(
            model_name='videogame',
            index=models.Index(fields=['name'], name='videogame_name_idx'),
        ),
    ]
